/*
Project: AdventureWorks Sales Analysis
File: 02_Product_Analysis.sql

Purpose:
Product performance analysis including:
- Sales by product category
- Sales by product subcategory
- Total revenue generated by products
*/

USE AdventureWorksDW2025;
GO

-- Sales performance by product category

SELECT
    pc.EnglishProductCategoryName AS ProductCategory,
    SUM(fs.SalesAmount) AS TotalSales,
    SUM(fs.OrderQuantity) AS UnitsSold
FROM FactInternetSales fs
JOIN DimProduct p
    ON fs.ProductKey = p.ProductKey
JOIN DimProductSubcategory psc
    ON p.ProductSubcategoryKey = psc.ProductSubcategoryKey
JOIN DimProductCategory pc
    ON psc.ProductCategoryKey = pc.ProductCategoryKey
GROUP BY
    pc.EnglishProductCategoryName
ORDER BY
    TotalSales DESC;


-- Top 10 products by revenue

SELECT TOP 10
    p.EnglishProductName AS ProductName,
    SUM(fs.SalesAmount) AS TotalSales,
    SUM(fs.OrderQuantity) AS UnitsSold
FROM FactInternetSales fs
JOIN DimProduct p
    ON fs.ProductKey = p.ProductKey
GROUP BY
    p.EnglishProductName
ORDER BY
    TotalSales DESC;